version: '3.8'

services:
  postgres_db:
    container_name: dev_postgres_db
    image: postgres:13-alpine
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    env_file:
      - .env
    networks:
      - dev_network
    volumes:
      - dev_pg_data:/var/lib/postgresql/data/
    restart: always

  server:
    container_name: dev_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    networks:
      - dev_network
    depends_on:
      - postgres_db
    volumes:
      - .:/app:rw,delegated
    restart: always

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    networks:
      - dev_network

networks:
  dev_network:
    name: dev_network

volumes:
  dev_pg_data: